### ISSUE TITLE
Question_generate not capable of detecting verbs

### ISSUE THREAD

**Issue by HajerMahjoub** [MLH-Fellowship/0.5.1-howDoIDiscord#27]
Question_generate is a method in the WikiHowAgent.py use spacy to detect id we did use verb after invoking howdoi to make very meaningful query but it's not working as NLTK or spacy both not capable to recognize  verbs like "program, print.... "as VERB not NOUN or PROPN

**Comment by rkbeatss** [comment]
i can help look into this if it is still relevant

**Comment by rkbeatss** [comment]
**this is what i realized:** 
if i do "how to program in python" or "how to print in python" then i get the correct tags because spaCy will be able to undersand the context of the sentence but if i only put "program in python" or "print in python", that's going to reduce spaCy's accuracy because the phrase is very ambiguous. is it even a full sentence? technically the tagger rn is pretty accurate because as far as the sentence goes, it could be seen as a noun.

**my suggestion:**
you already append the rest of the content with "how to" after you append the verbs, nouns, and proper nouns. what if you did that before you search for the verbs, nouns, and proper nouns itself. that way the spaCy pos tagger will be able to understand the full context of the sentence. 

i can test it out and create a pull request linking to this issue.

**Comment by HajerMahjoub** [comment]
@rkbeatss No even adding context to the verbs wasn't helpful I tried actually this solution but didn't work with nltk and spacy

**Comment by rkbeatss** [comment]
that's weird, im confused then. this is what i got testing some examples in my interpreter
![image](https://user-images.githubusercontent.com/23391143/84723450-97136b00-af53-11ea-823a-2c1ed64682ec.png)
and this is what the wikihowagent.py file prints for query "howdoi program in python":
![image](https://user-images.githubusercontent.com/23391143/84723631-08ebb480-af54-11ea-91b1-03bc542740de.png)

**Comment by HajerMahjoub** [comment]
@rkbeatss no worries starting from today will try to implement rasa agent that will be capable to detect verbs and entities of words that we need
